// Deterministic DDL generation. Never connects to a database.
import fs from "node:fs";
const contract = JSON.parse(fs.readFileSync("src/lib/analytics/lean-contracts.json", "utf8"));
const quote = (s) => {
  if (!/^[a-z_]+$/.test(s)) throw new Error("unsafe identifier");
  return `"${s}"`;
};
const type = (t) => {
  const types = {
    STRING: "text", ENUM: "text", BOOLEAN: "boolean", INTEGER: "bigint",
    DATE: "date", TIMESTAMP_UTC: "timestamptz",
    ISO_4217_CODE: "text", IANA_TIMEZONE: "text", "MAP<STRING,BOOLEAN?>": "jsonb",
  };
  if (types[t]) return types[t];
  if (/^DECIMAL\(\d+,\d+\)$/.test(t)) return t.replace("DECIMAL", "numeric");
  throw new Error(`unmapped ${t}`);
};
const header = `-- REVIEW ONLY. Apply manually to an approved test database first.
-- Generated by node scripts/analytics/generate-staging.mjs; no operational tables touched.
begin;
create schema lean_private;
create schema lean_analytics;
revoke all on schema lean_private, lean_analytics from public;
create table lean_private.publications (
  publication_id text primary key,
  state text not null default 'candidate' check (state in ('candidate','certified','rejected')),
  created_at timestamptz not null default now(),
  contract_version text not null,
  evidence_ref text,
  check (state <> 'certified' or evidence_ref is not null)
);
create table lean_private.expected_coverage (
  scope_key text primary key,
  domain text not null,
  source text not null,
  account_id text not null,
  from_date date not null,
  through_date date not null,
  history_start date,
  approval_ref text not null,
  check (from_date <= through_date)
);
create table lean_private.coverage (
  publication_id text not null references lean_private.publications,
  scope_key text not null references lean_private.expected_coverage,
  report_date date not null,
  outcome text not null check (outcome in ('complete','verified_empty','missing_auth','partial','schema_drift','failed')),
  source_count bigint check (source_count >= 0),
  written_count bigint check (written_count >= 0),
  evidence_ref text not null,
  primary key(publication_id, scope_key, report_date)
);
`;
const tables = contract.tables.map((t) => {
  const columns = t.fields.map(f => `  ${quote(f.name)} ${type(f.logicalType)}${f.nullable ? "" : " not null"}`);
  columns.push(`  primary key (${t.primaryKey.map(quote).join(", ")})`);
  columns.push(`  foreign key (publication_id) references lean_private.publications(publication_id)`);
  return `create table lean_private.${quote(t.name)} (\n${columns.join(",\n")}\n);\nalter table lean_private.${quote(t.name)} enable row level security;`;
}).join("\n");
const relationships = [
  ["order_items", "order_id", "orders", "order_id"],
  ["sales_ledger", "order_id", "orders", "order_id"],
  ["payments", "order_id", "orders", "order_id"],
  ["order_attribution", "order_id", "orders", "order_id"],
  ["order_item_offers", "order_item_id", "order_items", "order_item_id"],
].map(([child, key, parent, pk]) => `alter table lean_private.${quote(child)}
  add foreign key (${quote(key)}, publication_id)
  references lean_private.${quote(parent)} (${quote(pk)}, publication_id) deferrable initially deferred;`).join("\n");
fs.mkdirSync("sql/analytics", { recursive: true });
fs.writeFileSync("sql/analytics/001_staging.sql", header + tables + "\n" + relationships + `
-- No reader or PostHog grants yet. Identity and raw evidence are never exposed.
revoke all on all tables in schema lean_private from public;
commit;
`);
