/**
 * POST /api/admin/recommendations
 *
 * Accepts the flow metrics already fetched by /api/admin/sequences and returns
 * per-flow recommendations generated by:
 *   1. Heuristic rules (fast, deterministic flags)
 *   2. Claude commentary on flagged issues
 *
 * Auth: Firebase Bearer token (admin email allowlist).
 */

import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { adminAuth } from "@/lib/firebase-admin";
import { isAllowedAdminEmail } from "@/lib/adminEmailAllowlist";

const claude = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ─── Auth ─────────────────────────────────────────────────────────────────────

async function verifyAdmin(request: NextRequest): Promise<void> {
  const header = request.headers.get("Authorization") ?? "";
  const token = header.replace(/^Bearer\s+/i, "").trim();
  if (!token) throw new Error("Missing Authorization header");
  const decoded = await adminAuth.verifyIdToken(token, true);
  if (!decoded.email || !isAllowedAdminEmail(decoded.email)) {
    throw new Error("Forbidden");
  }
}

// ─── Types (mirrors sequences page) ──────────────────────────────────────────

interface StepMetrics {
  step: number;
  delayDays: number;
  triggerType: "schedule" | "event";
  sent: number;
  opened: number;
  clicked: number;
  replied: number;
}

interface FlowMetrics {
  users: { active: number; paused: number; completed: number; total: number };
  steps: StepMetrics[];
}

export interface Recommendation {
  severity: "warning" | "opportunity" | "info";
  step: number | null;
  title: string;
  detail: string;
  action: string;
}

// ─── Heuristic flags ──────────────────────────────────────────────────────────

interface Flag {
  severity: "warning" | "opportunity" | "info";
  step: number | null;
  description: string;
}

const FLOW_LABELS: Record<string, string> = {
  free: "Free",
  access: "Reserve Access",
  member: "Reserve Member",
  back9: "Back 9 (Legacy)",
};

function analyzeFlow(flowName: string, flow: FlowMetrics): Flag[] {
  const flags: Flag[] = [];
  const { users, steps } = flow;
  const total = users.total;

  if (total === 0) return [];

  // High paused ratio
  const pausedPct = users.paused / total;
  if (pausedPct > 0.3) {
    flags.push({
      severity: "warning",
      step: null,
      description: `${Math.round(pausedPct * 100)}% of users are paused (${users.paused}/${total}). High pause rate usually means many users replied — check the reply queue.`,
    });
  }

  // Low completion rate for a mature flow
  const completionPct = users.completed / total;
  if (total >= 10 && completionPct < 0.15) {
    flags.push({
      severity: "info",
      step: null,
      description: `Only ${Math.round(completionPct * 100)}% of users have completed this flow. Most users are still mid-sequence — revisit in 2–3 weeks.`,
    });
  }

  for (const s of steps) {
    if (s.sent < 3) continue; // not enough data

    const openRate = s.opened / s.sent;
    const clickRate = s.clicked / s.sent;
    const replyRate = s.replied / s.sent;

    // Low open rate
    if (openRate < 0.2) {
      flags.push({
        severity: "warning",
        step: s.step,
        description: `Step ${s.step + 1}: open rate is ${Math.round(openRate * 100)}% (${s.opened}/${s.sent}). Below 20% suggests the subject line is weak or the send time is off.`,
      });
    }

    // Good open rate, low click rate = weak CTA
    if (openRate >= 0.3 && clickRate < 0.05 && s.clicked > 0) {
      flags.push({
        severity: "warning",
        step: s.step,
        description: `Step ${s.step + 1}: opened well (${Math.round(openRate * 100)}%) but only ${Math.round(clickRate * 100)}% clicked. The CTA or link placement may be buried.`,
      });
    }

    // High reply rate = strong engagement
    if (replyRate >= 0.08) {
      flags.push({
        severity: "opportunity",
        step: s.step,
        description: `Step ${s.step + 1}: ${Math.round(replyRate * 100)}% reply rate — this email resonates strongly. Consider amplifying its angle in earlier steps.`,
      });
    }
  }

  // Step-to-step drop-off > 60%
  for (let i = 1; i < steps.length; i++) {
    const prev = steps[i - 1];
    const curr = steps[i];
    if (prev.sent < 5) continue;
    const dropPct = 1 - curr.sent / prev.sent;
    if (dropPct > 0.6) {
      flags.push({
        severity: "warning",
        step: curr.step,
        description: `Step ${curr.step + 1}: ${Math.round(dropPct * 100)}% drop-off from step ${prev.step + 1} (${prev.sent} → ${curr.sent} sent). Check if the trigger condition or delay for this step is misconfigured.`,
      });
    }
  }

  return flags;
}

// ─── Claude commentary ────────────────────────────────────────────────────────

async function generateRecommendations(
  flowName: string,
  flow: FlowMetrics,
  flags: Flag[]
): Promise<Recommendation[]> {
  if (flags.length === 0) {
    // No flags — return a single positive note without calling Claude
    return [
      {
        severity: "info",
        step: null,
        title: "Looking good",
        detail: "No significant issues detected in this flow.",
        action: "Keep monitoring as more sends accumulate.",
      },
    ];
  }

  const label = FLOW_LABELS[flowName] ?? flowName;
  const flagsText = flags
    .map((f) => `- [${f.severity.toUpperCase()}] ${f.description}`)
    .join("\n");

  const prompt = `You are a marketing advisor for Mully Reserve, a golf apparel & equipment membership brand.

You're reviewing the "${label}" email drip flow. Here are the detected issues and opportunities:

${flagsText}

For each item, provide a concise, actionable recommendation in this exact JSON format:
[
  {
    "severity": "warning" | "opportunity" | "info",
    "step": <step_number_0indexed_or_null_for_flow_level>,
    "title": "<5 words max>",
    "detail": "<1-2 sentences explaining the issue>",
    "action": "<1 concrete thing to change or test>"
  }
]

Rules:
- Match severity from the flag
- Be specific to golf/membership context
- "action" must be a single, testable change (e.g. "Test a subject line starting with the member's first name")
- Do not add generic marketing advice not grounded in the flags
- Output only valid JSON, no other text`;

  const msg = await claude.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    messages: [{ role: "user", content: prompt }],
  });

  const text = msg.content[0].type === "text" ? msg.content[0].text : "[]";

  // Strip markdown fences if present
  const clean = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();

  try {
    const parsed = JSON.parse(clean) as Recommendation[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return flags.map((f) => ({
      severity: f.severity,
      step: f.step,
      title: f.severity === "warning" ? "Issue detected" : "Opportunity",
      detail: f.description,
      action: "Review and test a targeted change.",
    }));
  }
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    await verifyAdmin(request);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unauthorized";
    return NextResponse.json({ error: msg }, { status: msg === "Forbidden" ? 403 : 401 });
  }

  let body: { flows?: Record<string, FlowMetrics> };
  try {
    body = await request.json() as { flows?: Record<string, FlowMetrics> };
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const flows = body.flows ?? {};
  if (Object.keys(flows).length === 0) {
    return NextResponse.json({ error: "No flow data provided" }, { status: 400 });
  }

  try {
    const results: Record<string, Recommendation[]> = {};

    await Promise.all(
      Object.entries(flows).map(async ([flowName, flow]) => {
        const flags = analyzeFlow(flowName, flow);
        results[flowName] = await generateRecommendations(flowName, flow, flags);
      })
    );

    return NextResponse.json({ flows: results });
  } catch (err) {
    console.error("[admin/recommendations] failed:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
