export interface Product {
  slug: string;
  name: string;
  brand: string;
  collection: string;
  price: number;
  reservePrice: number;
  images: string[];
  description: string;
  material: string;
  aboutBrand: string;
  whyWeLikeIt: string;
  sizing: string;
}

export const BRANDS = [
  "Titleist",
  "TravisMathew",
  "Peter Millar",
  "G/FORE",
  "Callaway",
  "Greyson",
] as const;

export const COLLECTIONS = [
  "Apparel",
  "Accessories",
  "Equipment",
  "Lifestyle",
] as const;

const placeholder = (i: number) =>
  `https://placehold.co/800x1000/1a3325/F5F1E8?text=Product+${i}`;

const placeholderSet = (i: number) => [
  `https://placehold.co/800x1000/1a3325/F5F1E8?text=Product+${i}+Front`,
  `https://placehold.co/800x1000/2a3d30/F5F1E8?text=Product+${i}+Back`,
  `https://placehold.co/800x1000/111111/F5F1E8?text=Product+${i}+Detail`,
];

export const products: Product[] = [
  // ── Titleist (5) ──
  {
    slug: "titleist-tour-soft-ball",
    name: "Tour Soft Golf Ball",
    brand: "Titleist",
    collection: "Equipment",
    price: 42,
    reservePrice: 34,
    images: placeholderSet(1),
    description: "A premium golf ball engineered for exceptional feel and distance. The Tour Soft features a larger, faster core and a thin 4CE grafted cover for outstanding performance off the tee and around the green.",
    material: "Ionomer cover, high-speed core",
    aboutBrand: "Titleist is the #1 ball in golf. Every product is developed with a relentless focus on performance, quality, and consistency — trusted by more professionals than any other brand.",
    whyWeLikeIt: "The Tour Soft bridges the gap between tour-level performance and everyday playability. It's the ball we recommend most to members looking for feel without sacrificing distance.",
    sizing: "Dozen (12 balls per box)",
  },
  {
    slug: "titleist-players-cap",
    name: "Players StaDry Cap",
    brand: "Titleist",
    collection: "Accessories",
    price: 36,
    reservePrice: 28,
    images: placeholderSet(2),
    description: "A waterproof performance cap designed for all-weather play. The StaDry construction keeps you dry while the structured fit maintains a clean, classic silhouette.",
    material: "100% polyester StaDry waterproof fabric",
    aboutBrand: "Titleist is the #1 ball in golf. Every product is developed with a relentless focus on performance, quality, and consistency — trusted by more professionals than any other brand.",
    whyWeLikeIt: "This cap looks good on and off the course. The waterproof tech actually works — we've tested it in some brutal rounds.",
    sizing: "One size fits most. Adjustable back closure.",
  },
  {
    slug: "titleist-hybrid-14-bag",
    name: "Hybrid 14 Stand Bag",
    brand: "Titleist",
    collection: "Equipment",
    price: 290,
    reservePrice: 235,
    images: placeholderSet(3),
    description: "A full-featured stand bag with 14-way top and convertible strap system. Designed for the player who walks and rides.",
    material: "Durable dobby polyester with reinforced base",
    aboutBrand: "Titleist is the #1 ball in golf. Every product is developed with a relentless focus on performance, quality, and consistency — trusted by more professionals than any other brand.",
    whyWeLikeIt: "The 14-way top keeps your clubs organized without the weight. This is the bag most of our staff carries.",
    sizing: "Standard stand bag — fits up to 14 clubs",
  },
  {
    slug: "titleist-vokey-wedge",
    name: "Vokey SM10 Wedge",
    brand: "Titleist",
    collection: "Equipment",
    price: 185,
    reservePrice: 155,
    images: placeholderSet(4),
    description: "The most played wedge on tour, now in its 10th generation. Progressive center of gravity and Spin Milled grooves deliver maximum spin and control.",
    material: "Soft carbon steel (8620)",
    aboutBrand: "Titleist is the #1 ball in golf. Every product is developed with a relentless focus on performance, quality, and consistency — trusted by more professionals than any other brand.",
    whyWeLikeIt: "There's a reason more tour players play Vokey than any other wedge. The spin consistency is unmatched.",
    sizing: "Available in 46°–62° with multiple grind options",
  },
  {
    slug: "titleist-microfiber-towel",
    name: "Players Microfiber Towel",
    brand: "Titleist",
    collection: "Accessories",
    price: 28,
    reservePrice: 22,
    images: placeholderSet(5),
    description: "Waffle-weave microfiber towel with carabiner clip. Oversized for full club and ball cleaning.",
    material: "Microfiber waffle weave",
    aboutBrand: "Titleist is the #1 ball in golf. Every product is developed with a relentless focus on performance, quality, and consistency — trusted by more professionals than any other brand.",
    whyWeLikeIt: "It's a towel, but it's a really good towel. The waffle texture picks up everything and the clip keeps it accessible.",
    sizing: "20\" x 40\" — one size",
  },

  // ── TravisMathew (5) ──
  {
    slug: "travismathew-heater-polo",
    name: "Heater Polo",
    brand: "TravisMathew",
    collection: "Apparel",
    price: 95,
    reservePrice: 72,
    images: placeholderSet(6),
    description: "A refined 4-way stretch polo with subtle texture and a modern fit. The Heater features UPF 50 protection and moisture-wicking technology for all-day comfort.",
    material: "90% polyester, 10% elastane — 4-way stretch",
    aboutBrand: "TravisMathew blends California lifestyle with performance golf apparel. Every piece is designed to transition seamlessly from the course to dinner.",
    whyWeLikeIt: "The fit is dialed. It looks like a $150 polo from the big luxury houses, performs like true technical golf wear, and costs less than both.",
    sizing: "True to size. S / M / L / XL / XXL",
  },
  {
    slug: "travismathew-baja-short",
    name: "Baja Short",
    brand: "TravisMathew",
    collection: "Apparel",
    price: 80,
    reservePrice: 62,
    images: placeholderSet(7),
    description: "A lightweight, breathable short with a clean flat front and just enough stretch to move naturally through your swing.",
    material: "92% polyester, 8% elastane",
    aboutBrand: "TravisMathew blends California lifestyle with performance golf apparel. Every piece is designed to transition seamlessly from the course to dinner.",
    whyWeLikeIt: "The most versatile short in the shop. Course-approved, but you'll wear them everywhere else too.",
    sizing: "Waist sizes 30–38. 9\" inseam.",
  },
  {
    slug: "travismathew-cloud-quarter-zip",
    name: "Cloud Quarter-Zip",
    brand: "TravisMathew",
    collection: "Apparel",
    price: 115,
    reservePrice: 88,
    images: placeholderSet(8),
    description: "Ultra-soft mid-layer with a brushed interior and structured collar. The go-to layer for morning rounds and cool evenings.",
    material: "87% polyester, 13% elastane — brushed fleece interior",
    aboutBrand: "TravisMathew blends California lifestyle with performance golf apparel. Every piece is designed to transition seamlessly from the course to dinner.",
    whyWeLikeIt: "The brushed interior feels incredible. This is the piece you'll throw in your bag every single round, regardless of the forecast.",
    sizing: "True to size. S / M / L / XL / XXL",
  },
  {
    slug: "travismathew-mesa-hat",
    name: "Mesa Snapback",
    brand: "TravisMathew",
    collection: "Accessories",
    price: 35,
    reservePrice: 28,
    images: placeholderSet(9),
    description: "A structured snapback with a clean profile and subtle branding. Moisture-wicking sweatband keeps you comfortable through 18.",
    material: "Polyester performance fabric",
    aboutBrand: "TravisMathew blends California lifestyle with performance golf apparel. Every piece is designed to transition seamlessly from the course to dinner.",
    whyWeLikeIt: "Low-key branding, great shape out of the box. It just works.",
    sizing: "One size fits most. Snapback closure.",
  },
  {
    slug: "travismathew-wanderlust-hoodie",
    name: "Wanderlust Hoodie",
    brand: "TravisMathew",
    collection: "Lifestyle",
    price: 130,
    reservePrice: 98,
    images: placeholderSet(10),
    description: "A premium performance hoodie with a relaxed fit. Designed for post-round comfort with enough structure to wear out.",
    material: "Cotton-polyester blend with peached finish",
    aboutBrand: "TravisMathew blends California lifestyle with performance golf apparel. Every piece is designed to transition seamlessly from the course to dinner.",
    whyWeLikeIt: "The crossover piece. Golf bag to coffee shop to dinner — it handles everything.",
    sizing: "Relaxed fit. Size down for a trimmer look. S–XXL.",
  },

  // ── Peter Millar (5) ──
  {
    slug: "peter-millar-crown-polo",
    name: "Crown Crafted Polo",
    brand: "Peter Millar",
    collection: "Apparel",
    price: 148,
    reservePrice: 118,
    images: placeholderSet(11),
    description: "The Crown Crafted line represents the pinnacle of Peter Millar's performance fabric development. This polo features a refined stretch piqué with a tailored fit.",
    material: "100% performance polyester — stretch piqué",
    aboutBrand: "Peter Millar is the standard in luxury golf apparel. Born from a commitment to craftsmanship, every piece balances sophistication with genuine technical performance.",
    whyWeLikeIt: "This is the polo that makes you look like you belong at any club in the world. The fabric quality is a tier above everything else at this price.",
    sizing: "Tailored fit. Consider sizing up if between sizes. S–XXL.",
  },
  {
    slug: "peter-millar-eb66-trouser",
    name: "EB66 Performance Trouser",
    brand: "Peter Millar",
    collection: "Apparel",
    price: 165,
    reservePrice: 132,
    images: placeholderSet(12),
    description: "A technical trouser with a refined appearance. The EB66 fabric delivers 4-way stretch and moisture management in a silhouette that looks custom-tailored.",
    material: "EB66 performance stretch — polyester/elastane",
    aboutBrand: "Peter Millar is the standard in luxury golf apparel. Born from a commitment to craftsmanship, every piece balances sophistication with genuine technical performance.",
    whyWeLikeIt: "These look like dress trousers but perform like athletic wear. The EB66 fabric is truly special — you feel the difference immediately.",
    sizing: "Waist 30–40. 32\" inseam standard. Tailored fit.",
  },
  {
    slug: "peter-millar-hyperlight-vest",
    name: "Hyperlight Quilted Vest",
    brand: "Peter Millar",
    collection: "Apparel",
    price: 198,
    reservePrice: 158,
    images: placeholderSet(13),
    description: "A lightweight, packable quilted vest with synthetic insulation. The Hyperlight construction adds warmth without restricting your swing.",
    material: "Nylon shell with synthetic fill insulation",
    aboutBrand: "Peter Millar is the standard in luxury golf apparel. Born from a commitment to craftsmanship, every piece balances sophistication with genuine technical performance.",
    whyWeLikeIt: "Layer it under a jacket or wear it alone — it always looks sharp. The packability means it lives in your golf bag year-round.",
    sizing: "True to size. S / M / L / XL / XXL",
  },
  {
    slug: "peter-millar-crown-belt",
    name: "Crown Crafted Belt",
    brand: "Peter Millar",
    collection: "Accessories",
    price: 125,
    reservePrice: 98,
    images: placeholderSet(14),
    description: "Full-grain Italian leather belt with a brushed nickel buckle. The kind of accessory that elevates everything around it.",
    material: "Full-grain Italian leather",
    aboutBrand: "Peter Millar is the standard in luxury golf apparel. Born from a commitment to craftsmanship, every piece balances sophistication with genuine technical performance.",
    whyWeLikeIt: "A great belt is the most underrated accessory in golf. This one will last years and only get better.",
    sizing: "Sizes 30–42. Measure your waist for best fit.",
  },
  {
    slug: "peter-millar-seaside-short",
    name: "Seaside Wash Short",
    brand: "Peter Millar",
    collection: "Apparel",
    price: 110,
    reservePrice: 88,
    images: placeholderSet(15),
    description: "A garment-washed performance short with a lived-in feel. The Seaside delivers a relaxed aesthetic backed by serious stretch and moisture-wicking tech.",
    material: "Cotton-blend with mechanical stretch",
    aboutBrand: "Peter Millar is the standard in luxury golf apparel. Born from a commitment to craftsmanship, every piece balances sophistication with genuine technical performance.",
    whyWeLikeIt: "That perfectly broken-in feel on day one. Pairs with everything and the stretch is real.",
    sizing: "Waist 30–38. 8.5\" inseam.",
  },

  // ── G/FORE (5) ──
  {
    slug: "gfore-gallivanter-shoe",
    name: "Gallivanter Golf Shoe",
    brand: "G/FORE",
    collection: "Equipment",
    price: 225,
    reservePrice: 185,
    images: placeholderSet(16),
    description: "G/FORE's signature waterproof golf shoe. The Gallivanter combines Italian leather construction with a performance rubber outsole for grip and style that stands apart.",
    material: "Italian waterproof leather upper, rubber outsole",
    aboutBrand: "G/FORE brings disruptive design to the golf world. Bold colors, premium materials, and a refusal to blend in — for the player with a point of view.",
    whyWeLikeIt: "These are the shoes that get compliments every single round. Italian leather, waterproof, and they look like nothing else on the course.",
    sizing: "Runs true. Half sizes available. 7–13.",
  },
  {
    slug: "gfore-delta-force-glove",
    name: "Delta Force Glove",
    brand: "G/FORE",
    collection: "Accessories",
    price: 38,
    reservePrice: 30,
    images: placeholderSet(17),
    description: "A Cabretta leather golf glove with G/FORE's signature color pop. Premium feel, precise fit, and the look that started a movement.",
    material: "AAA Cabretta leather",
    aboutBrand: "G/FORE brings disruptive design to the golf world. Bold colors, premium materials, and a refusal to blend in — for the player with a point of view.",
    whyWeLikeIt: "The best-feeling glove in the shop. The Cabretta leather is buttery and the color options let you make a statement.",
    sizing: "S / M / ML / L / XL. Snug fit recommended.",
  },
  {
    slug: "gfore-ribbed-polo",
    name: "Ribbed Knit Polo",
    brand: "G/FORE",
    collection: "Apparel",
    price: 135,
    reservePrice: 108,
    images: placeholderSet(18),
    description: "A textured ribbed knit polo with a retro-inspired silhouette. This is golf fashion that doesn't look like golf fashion.",
    material: "Cotton-polyester rib knit blend",
    aboutBrand: "G/FORE brings disruptive design to the golf world. Bold colors, premium materials, and a refusal to blend in — for the player with a point of view.",
    whyWeLikeIt: "If you want to stand out without trying too hard, this is the polo. The ribbed texture is subtle but distinct.",
    sizing: "Slim fit. Size up one if you prefer relaxed. S–XXL.",
  },
  {
    slug: "gfore-transporter-tote",
    name: "Transporter Tote",
    brand: "G/FORE",
    collection: "Lifestyle",
    price: 175,
    reservePrice: 140,
    images: placeholderSet(19),
    description: "A structured tote built for the course and beyond. Features a padded laptop sleeve, shoe compartment, and premium hardware.",
    material: "Coated canvas with leather trim",
    aboutBrand: "G/FORE brings disruptive design to the golf world. Bold colors, premium materials, and a refusal to blend in — for the player with a point of view.",
    whyWeLikeIt: "Your golf bag, work bag, and weekender all in one. The shoe compartment is genius.",
    sizing: "One size — 18\" x 14\" x 8\"",
  },
  {
    slug: "gfore-circle-g-cap",
    name: "Circle G Snapback",
    brand: "G/FORE",
    collection: "Accessories",
    price: 42,
    reservePrice: 34,
    images: placeholderSet(20),
    description: "A structured snapback featuring the iconic Circle G logo. Performance moisture-wicking fabric with a pre-curved brim.",
    material: "Performance polyester with moisture-wicking sweatband",
    aboutBrand: "G/FORE brings disruptive design to the golf world. Bold colors, premium materials, and a refusal to blend in — for the player with a point of view.",
    whyWeLikeIt: "Clean logo, great shape, comfortable fit. The G/FORE cap that works with everything.",
    sizing: "One size fits most. Snapback closure.",
  },

  // ── Callaway (5) ──
  {
    slug: "callaway-chrome-soft-ball",
    name: "Chrome Soft Golf Ball",
    brand: "Callaway",
    collection: "Equipment",
    price: 50,
    reservePrice: 40,
    images: placeholderSet(21),
    description: "A tour-level golf ball with a Hyper Elastic SoftFast Core for maximum speed and spin. The Chrome Soft delivers the full package of distance, feel, and control.",
    material: "Urethane cover, graphene-infused core",
    aboutBrand: "Callaway pushes the boundaries of golf technology. From AI-designed club faces to precision-engineered balls, Callaway is where innovation meets performance.",
    whyWeLikeIt: "If you're not playing a Pro V1, you're probably playing a Chrome Soft. The spin separation between driver and wedge is the real story here.",
    sizing: "Dozen (12 balls per box)",
  },
  {
    slug: "callaway-paradym-driver",
    name: "Paradym Ai Driver",
    brand: "Callaway",
    collection: "Equipment",
    price: 599,
    reservePrice: 479,
    images: placeholderSet(22),
    description: "AI-designed with a 360° Carbon Chassis. The Paradym delivers exceptional ball speed, forgiveness, and a flight that maximizes your distance.",
    material: "Triaxial carbon crown, forged carbon sole, titanium face",
    aboutBrand: "Callaway pushes the boundaries of golf technology. From AI-designed club faces to precision-engineered balls, Callaway is where innovation meets performance.",
    whyWeLikeIt: "The sound. The speed. The forgiveness on off-center hits. This is the driver that changed the conversation about what AI can do in club design.",
    sizing: "9°, 10.5°, 12° loft options. Regular, Stiff, X-Stiff shafts.",
  },
  {
    slug: "callaway-fairway-c-headcover",
    name: "Fairway C Headcover",
    brand: "Callaway",
    collection: "Accessories",
    price: 30,
    reservePrice: 24,
    images: placeholderSet(23),
    description: "A premium synthetic leather headcover with magnetic closure. Designed to fit fairway woods with a secure, easy on-and-off design.",
    material: "Synthetic leather with plush interior lining",
    aboutBrand: "Callaway pushes the boundaries of golf technology. From AI-designed club faces to precision-engineered balls, Callaway is where innovation meets performance.",
    whyWeLikeIt: "The magnetic closure is a small thing that makes a big difference. No fumbling on the tee box.",
    sizing: "Fits fairway woods 3W–7W",
  },
  {
    slug: "callaway-dawn-patrol-glove",
    name: "Dawn Patrol Glove",
    brand: "Callaway",
    collection: "Accessories",
    price: 18,
    reservePrice: 14,
    images: placeholderSet(24),
    description: "An affordable premium leather glove with an opti-fit closure for a secure, comfortable fit. Premium feel at a value price.",
    material: "Full Cabretta leather",
    aboutBrand: "Callaway pushes the boundaries of golf technology. From AI-designed club faces to precision-engineered balls, Callaway is where innovation meets performance.",
    whyWeLikeIt: "Best value glove in golf. Full Cabretta leather at this price is unheard of. Stock up.",
    sizing: "S / M / ML / L / XL / Cadet sizes available.",
  },
  {
    slug: "callaway-striped-mesh-polo",
    name: "Striped Mesh Polo",
    brand: "Callaway",
    collection: "Apparel",
    price: 75,
    reservePrice: 58,
    images: placeholderSet(25),
    description: "A ventilated mesh polo with engineered stripe pattern. Opti-Dri technology wicks moisture while Opti-Stretch allows full range of motion.",
    material: "100% polyester with Opti-Dri and Opti-Stretch",
    aboutBrand: "Callaway pushes the boundaries of golf technology. From AI-designed club faces to precision-engineered balls, Callaway is where innovation meets performance.",
    whyWeLikeIt: "Technical golf polo that doesn't scream \"technical golf polo.\" The mesh ventilation on hot days is a game-changer.",
    sizing: "True to size. S / M / L / XL / XXL",
  },

  // ── Greyson (5) ──
  {
    slug: "greyson-wolf-polo",
    name: "Wolf Pack Polo",
    brand: "Greyson",
    collection: "Apparel",
    price: 120,
    reservePrice: 95,
    images: placeholderSet(26),
    description: "Greyson's signature polo featuring their iconic Wolf motif. Premium Japanese technical fabric with a modern athletic fit.",
    material: "Japanese performance fabric — 86% nylon, 14% elastane",
    aboutBrand: "Greyson reimagines what golf apparel can be. Rooted in sport but designed with fashion-forward sensibility — for the player who sees golf as part of their lifestyle.",
    whyWeLikeIt: "The Japanese fabric is on another level. Lightweight, breathable, with a hand feel that you won't find anywhere else in golf.",
    sizing: "Athletic fit. True to size. S / M / L / XL / XXL",
  },
  {
    slug: "greyson-sequoia-jogger",
    name: "Sequoia Jogger",
    brand: "Greyson",
    collection: "Lifestyle",
    price: 145,
    reservePrice: 115,
    images: placeholderSet(27),
    description: "A tailored jogger that bridges performance and lifestyle. Course-approved at most clubs, but designed to look good everywhere.",
    material: "4-way stretch woven fabric with DWR finish",
    aboutBrand: "Greyson reimagines what golf apparel can be. Rooted in sport but designed with fashion-forward sensibility — for the player who sees golf as part of their lifestyle.",
    whyWeLikeIt: "The jogger that finally got approved at every course we tested it at. Technical, tailored, and versatile.",
    sizing: "S / M / L / XL / XXL. 30\" inseam.",
  },
  {
    slug: "greyson-tundra-vest",
    name: "Tundra Puffer Vest",
    brand: "Greyson",
    collection: "Apparel",
    price: 225,
    reservePrice: 180,
    images: placeholderSet(28),
    description: "A premium down-alternative puffer vest with a sleek silhouette. Water-resistant shell and packable construction for easy transport.",
    material: "Nylon ripstop with PrimaLoft insulation",
    aboutBrand: "Greyson reimagines what golf apparel can be. Rooted in sport but designed with fashion-forward sensibility — for the player who sees golf as part of their lifestyle.",
    whyWeLikeIt: "The proportions are perfect — not too puffy, not too flat. It layers beautifully and packs down to almost nothing.",
    sizing: "True to size. S / M / L / XL / XXL",
  },
  {
    slug: "greyson-spirit-animal-cap",
    name: "Spirit Animal Cap",
    brand: "Greyson",
    collection: "Accessories",
    price: 48,
    reservePrice: 38,
    images: placeholderSet(29),
    description: "A unstructured performance cap featuring Greyson's signature wolf embroidery. Lightweight, breathable, and effortlessly cool.",
    material: "Performance polyester with moisture-wicking sweatband",
    aboutBrand: "Greyson reimagines what golf apparel can be. Rooted in sport but designed with fashion-forward sensibility — for the player who sees golf as part of their lifestyle.",
    whyWeLikeIt: "The unstructured silhouette and wolf logo make this the coolest hat in your rotation. Period.",
    sizing: "One size fits most. Adjustable strapback.",
  },
  {
    slug: "greyson-montauk-quarter-zip",
    name: "Montauk Quarter-Zip",
    brand: "Greyson",
    collection: "Apparel",
    price: 165,
    reservePrice: 132,
    images: placeholderSet(30),
    description: "A lightweight technical layer with a refined aesthetic. The Montauk features a bonded construction that blocks wind while allowing airflow where you need it.",
    material: "Bonded stretch fabric — wind-resistant, breathable",
    aboutBrand: "Greyson reimagines what golf apparel can be. Rooted in sport but designed with fashion-forward sensibility — for the player who sees golf as part of their lifestyle.",
    whyWeLikeIt: "Wind protection without bulk. This is the layer that lives in your bag from October through April.",
    sizing: "True to size. S / M / L / XL / XXL",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
