-- The Send Gate — schema for src/lib/email/gate.ts
--
-- Project ref: xnfjdbpjuaezxjgargto
--
-- NOT YET APPLIED. This file is checked in only; nothing in this PR runs it.
--
-- Ordering matters: `gate.ts` queries suppression_list.scope and send_log on
-- every send. Until this migration is applied, those queries error, and the
-- gate's fail-closed policy will block every campaign and lifecycle send (see
-- dependencyFailure() in gate.ts). Apply this BEFORE the code ships.

begin;

-- ─── 1. suppression_list.scope ───────────────────────────────────────────────
-- One source of truth for suppression, now channel-aware. All 1,859 existing
-- rows are bot_detection, which is a whole-person block, so `default 'all'`
-- backfills them correctly and no separate UPDATE is needed.

alter table public.suppression_list
  add column if not exists scope text not null default 'all';

alter table public.suppression_list
  drop constraint if exists suppression_list_scope_check;

alter table public.suppression_list
  add constraint suppression_list_scope_check
  check (scope in ('email', 'sms', 'all'));

create index if not exists suppression_list_email_scope_idx
  on public.suppression_list (email, scope);

-- ─── 2. send_log ─────────────────────────────────────────────────────────────
-- Built fresh. No historical send data is migrated, so the frequency cap starts
-- from zero for everyone on the day this ships.

create table if not exists public.send_log (
  id                  bigint generated by default as identity primary key,
  email               text not null,
  phone_e164          text,
  send_class          text not null,
  flow                text,
  category            text,
  step                integer,
  provider            text not null,
  provider_message_id text,
  sent_at             timestamptz not null default now(),
  constraint send_log_send_class_check
    check (send_class in ('transactional', 'lifecycle', 'campaign'))
);

-- Serves the frequency-cap query: count where email = $1 and sent_at >= $2.
create index if not exists send_log_email_sent_at_idx
  on public.send_log (email, sent_at desc);

alter table public.send_log enable row level security;

-- ─── 3. Enrollment ───────────────────────────────────────────────────────────
-- Intentionally NOT created here.
--
-- Enrollment state lives in Firestore at `email_sequences/{uid}` and that is
-- still the source of truth. The gate's flow-exclusivity check reads Firestore
-- directly (checkFlowExclusivity in gate.ts). Creating a Postgres enrollment
-- table now would give us two writers and no reconciliation.
--
-- TODO(phase-6b): migrate enrollment out of Firestore into Postgres so the gate
-- reads a single database, then move flow exclusivity onto that table.

commit;
