-- REVIEW ONLY. Apply manually to an approved test database first.
-- Generated by node scripts/analytics/generate-staging.mjs; no operational tables touched.
begin;
create schema lean_private;
create schema lean_analytics;
revoke all on schema lean_private, lean_analytics from public;
create table lean_private.publications (
  publication_id text primary key,
  state text not null default 'candidate' check (state in ('candidate','certified','rejected')),
  created_at timestamptz not null default now(),
  contract_version text not null,
  evidence_ref text,
  check (state <> 'certified' or evidence_ref is not null)
);
create table lean_private.expected_coverage (
  scope_key text primary key,
  domain text not null,
  source text not null,
  account_id text not null,
  from_date date not null,
  through_date date not null,
  history_start date,
  approval_ref text not null,
  check (from_date <= through_date)
);
create table lean_private.coverage (
  publication_id text not null references lean_private.publications,
  scope_key text not null references lean_private.expected_coverage,
  report_date date not null,
  outcome text not null check (outcome in ('complete','verified_empty','missing_auth','partial','schema_drift','failed')),
  source_count bigint check (source_count >= 0),
  written_count bigint check (written_count >= 0),
  evidence_ref text not null,
  primary key(publication_id, scope_key, report_date)
);
create table lean_private."customers" (
  "customer_id" text not null,
  "publication_id" text not null,
  "identity_status" text not null,
  "analytics_permitted" boolean not null,
  "history_complete" boolean not null,
  "first_eligible_order_id" text,
  "first_eligible_order_at" timestamptz,
  "acquisition_date" date,
  primary key ("customer_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."customers" enable row level security;
create table lean_private."identity_map" (
  "source_namespace" text not null,
  "source_identifier" text not null,
  "customer_id" text,
  "valid_from" timestamptz not null,
  "valid_to" timestamptz,
  "evidence_type" text not null,
  "evidence_ref" text not null,
  "mapping_version" text not null,
  "resolution_status" text not null,
  "consent_status" text not null,
  "removal_status" text not null,
  "publication_id" text not null,
  primary key ("source_namespace", "source_identifier", "valid_from", "mapping_version", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."identity_map" enable row level security;
create table lean_private."orders" (
  "order_id" text not null,
  "source_order_id" text not null,
  "shop_id" text not null,
  "customer_id" text,
  "checkout_id" text,
  "created_at" timestamptz not null,
  "paid_at" timestamptz,
  "commerce_source" text not null,
  "eligibility_status" text not null,
  "checkout_session_key" text,
  "checkout_link_status" text not null,
  "checkout_link_method" text not null,
  "evidence_ref" text,
  "link_version" text not null,
  "shipping_country" text,
  "shipping_region" text,
  "source_updated_at" timestamptz not null,
  "purchase_date" date,
  "acquisition_eligible" boolean not null,
  "source_currency" text not null,
  "report_currency" text not null,
  "purchase_merchandise_gross_usd" numeric(20,6),
  "purchase_discount_usd" numeric(20,6),
  "purchase_merchandise_net_usd" numeric(20,6),
  "publication_id" text not null,
  primary key ("order_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."orders" enable row level security;
create table lean_private."order_items" (
  "order_item_id" text not null,
  "order_id" text not null,
  "source_line_id" text not null,
  "sku" text,
  "product_id" text,
  "quantity" numeric(20,6) not null,
  "item_class" text not null,
  "purchase_value_complete" boolean not null,
  "source_currency" text not null,
  "report_currency" text not null,
  "unit_price_usd" numeric(20,6),
  "purchase_gross_usd" numeric(20,6),
  "purchase_discount_usd" numeric(20,6),
  "purchase_net_usd" numeric(20,6),
  "unit_cost_usd" numeric(20,6),
  "cost_evidence_ref" text,
  "publication_id" text not null,
  primary key ("order_item_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."order_items" enable row level security;
create table lean_private."sales_ledger" (
  "ledger_entry_id" text not null,
  "source_movement_id" text not null,
  "order_id" text not null,
  "order_item_id" text,
  "component" text not null,
  "movement_kind" text not null,
  "effective_at" timestamptz not null,
  "report_date" date not null,
  "source_amount" numeric(20,6) not null,
  "source_currency" text not null,
  "report_currency" text not null,
  "amount_usd" numeric(20,6),
  "sales_eligible" boolean not null,
  "product_allocation_status" text not null,
  "reverses_entry_id" text,
  "publication_id" text not null,
  primary key ("ledger_entry_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."sales_ledger" enable row level security;
create table lean_private."payments" (
  "payment_id" text not null,
  "source_transaction_id" text not null,
  "order_id" text not null,
  "parent_payment_id" text,
  "transaction_kind" text not null,
  "transaction_status" text not null,
  "settled_at" timestamptz,
  "report_date" date,
  "source_amount" numeric(20,6) not null,
  "source_currency" text not null,
  "report_currency" text not null,
  "cash_amount_usd" numeric(20,6),
  "cash_eligible" boolean not null,
  "publication_id" text not null,
  primary key ("payment_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."payments" enable row level security;
create table lean_private."sessions" (
  "session_key" text not null,
  "source_session_id" text not null,
  "sessionization_version" text not null,
  "started_at" timestamptz not null,
  "ended_at" timestamptz,
  "report_date" date not null,
  "entry_page" text,
  "traffic_source" text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "campaign_id" text,
  "device_type" text,
  "observed_geo" text,
  "customer_id" text,
  "identity_status" text not null,
  "eligible_event_count" bigint,
  "funnel_flags" jsonb,
  "behavior_complete" boolean not null,
  "conversion_window_complete" boolean not null,
  "analytics_eligible" boolean not null,
  "converted_session" boolean,
  "funnel_version" text not null,
  "publication_id" text not null,
  primary key ("session_key", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."sessions" enable row level security;
create table lean_private."marketing_spend_daily" (
  "provider" text not null,
  "account_id" text not null,
  "campaign_key" text not null,
  "source_campaign_id" text,
  "report_date" date not null,
  "base_report_id" text not null,
  "source_timezone" text not null,
  "source_currency" text not null,
  "source_amount" numeric(20,6) not null,
  "report_currency" text not null,
  "spend_usd" numeric(20,6),
  "impressions" bigint,
  "clicks" bigint,
  "click_definition" text,
  "channel" text not null,
  "source_updated_at" timestamptz not null,
  "publication_id" text not null,
  primary key ("provider", "account_id", "campaign_key", "report_date", "base_report_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."marketing_spend_daily" enable row level security;
create table lean_private."order_attribution" (
  "order_id" text not null,
  "model_version" text not null,
  "publication_id" text not null,
  "acquisition_session_key" text,
  "touch_event_key" text,
  "channel" text not null,
  "campaign_id" text,
  "attribution_status" text not null,
  "lookback_days" bigint not null,
  "conversion_time_basis" text not null,
  "credit_weight" numeric(12,9) not null,
  "conversion_date" date not null,
  "attribution_complete" boolean not null,
  primary key ("order_id", "model_version", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."order_attribution" enable row level security;
create table lean_private."order_item_offers" (
  "order_item_id" text not null,
  "offer_id" text not null,
  "membership_basis" text not null,
  "evidence_ref" text not null,
  "offer_mapping_version" text not null,
  "publication_id" text not null,
  primary key ("order_item_id", "offer_id", "publication_id"),
  foreign key (publication_id) references lean_private.publications(publication_id)
);
alter table lean_private."order_item_offers" enable row level security;
alter table lean_private."order_items"
  add foreign key ("order_id", publication_id)
  references lean_private."orders" ("order_id", publication_id) deferrable initially deferred;
alter table lean_private."sales_ledger"
  add foreign key ("order_id", publication_id)
  references lean_private."orders" ("order_id", publication_id) deferrable initially deferred;
alter table lean_private."payments"
  add foreign key ("order_id", publication_id)
  references lean_private."orders" ("order_id", publication_id) deferrable initially deferred;
alter table lean_private."order_attribution"
  add foreign key ("order_id", publication_id)
  references lean_private."orders" ("order_id", publication_id) deferrable initially deferred;
alter table lean_private."order_item_offers"
  add foreign key ("order_item_id", publication_id)
  references lean_private."order_items" ("order_item_id", publication_id) deferrable initially deferred;
-- No reader or PostHog grants yet. Identity and raw evidence are never exposed.
revoke all on all tables in schema lean_private from public;
commit;
