-- Operator-only domain release. Null/withheld metrics stay null/withheld.
-- A publication is frozen after one selection; add domains in a new build.
begin;
create function public.lean_scoped_release(p_run text,p_project_ref text,p_domains text[],
  p_expected_previous jsonb,p_approval text,p_reconciliation text,p_actor text)
returns void language plpgsql security definer set search_path=pg_catalog as $$
declare r lean_private.full_builds; pub text; t text; previous text; ready_rows bigint;
  allowed text[] := array['store_daily','product_daily','acquisition_daily','customer_cohorts','funnel_daily'];
begin
  if p_domains is null or cardinality(p_domains) not between 1 and 5 or
    not(p_domains<@allowed) or array_position(p_domains,null) is not null or
    (select count(distinct d) from unnest(p_domains) d)<>cardinality(p_domains) or
    p_expected_previous is null or jsonb_typeof(p_expected_previous)<>'object' or
    not(p_expected_previous ?& p_domains) or
    (select count(*) from jsonb_object_keys(p_expected_previous))<>cardinality(p_domains) or
    coalesce(length(trim(p_approval)),0)=0 or coalesce(length(trim(p_reconciliation)),0)=0 or
    coalesce(length(trim(p_actor)),0)=0 then raise exception 'scoped release review required'; end if;
  select * into r from lean_private.full_builds where run_id=p_run and project_ref=p_project_ref for update;
  if not found or not r.enabled or r.completed_at is null then raise exception 'full build not complete'; end if;
  pub := 'full:'||p_run;
  perform 1 from lean_private.publications where publication_id=pub and state='candidate' for update;
  if not found then raise exception 'candidate required'; end if;
  lock table lean_private.selected_publications in exclusive mode;
  foreach t in array p_domains loop
    select publication_id into previous from lean_private.selected_publications where domain=t;
    if previous is distinct from p_expected_previous->>t then raise exception 'selection changed; re-read before retry'; end if;
    -- Readiness is generated by the builder's independent per-metric evidence
    -- gates. Review still required. Never turn missing evidence into readiness.
    execute format('select count(*) from lean_private.%I where publication_id=$1 and
      exists(select 1 from jsonb_each_text(readiness) e where e.value=''observed_unverified'')',
      'report_'||t) into ready_rows using pub;
    if ready_rows=0 then raise exception 'no verified observations for selected domain'; end if;
    insert into lean_private.certifications(publication_id,domain,evidence_ref,source_reconciliation_ref,approved_by)
      values(pub,t,p_approval,p_reconciliation,p_actor);
    execute format('update lean_private.%I set is_stale=false,readiness=(
      select jsonb_object_agg(k,case when v=''observed_unverified'' then ''ready'' else v end)
      from jsonb_each_text(readiness) e(k,v)) where publication_id=$1','report_'||t) using pub;
  end loop;
  update lean_private.publications set state='certified',evidence_ref=p_approval where publication_id=pub;
  foreach t in array p_domains loop
    perform public.lean_select_publication(t,pub,p_expected_previous->>t,p_approval);
  end loop;
end $$;

create function public.lean_scoped_export(p_run text,p_project_ref text,p_domains text[],p_approval text,p_actor text)
returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare r lean_private.full_builds; pub text; t text; n bigint; counts jsonb := '{}';
  allowed text[] := array['store_daily','product_daily','acquisition_daily','customer_cohorts','funnel_daily'];
begin
  if p_domains is null or cardinality(p_domains) not between 1 and 5 or
    not(p_domains<@allowed) or array_position(p_domains,null) is not null or
    (select count(distinct d) from unnest(p_domains) d)<>cardinality(p_domains) or
    coalesce(length(trim(p_approval)),0)=0 or coalesce(length(trim(p_actor)),0)=0
    then raise exception 'scoped export review required'; end if;
  select * into r from lean_private.full_builds where run_id=p_run and project_ref=p_project_ref for share;
  if not found or not r.enabled or r.completed_at is null then raise exception 'full build not complete'; end if;
  pub := 'full:'||p_run;
  lock table lean_private.selected_publications in share mode;
  perform 1 from lean_private.publications where publication_id=pub and state='certified' for share;
  if not found or (select count(*) from lean_private.selected_publications
    where domain=any(p_domains) and publication_id=pub and not is_stale)<>cardinality(p_domains)
    then raise exception 'scoped selection required'; end if;
  lock table lean_private.export_audit in exclusive mode;
  foreach t in array p_domains loop
    execute format('delete from lean_export.%I',t);
    execute format('insert into lean_export.%I select * from lean_analytics.%I where publication_id=$1',t,t) using pub;
    get diagnostics n = row_count;
    counts := counts||jsonb_build_object(t,n);
  end loop;
  insert into lean_private.export_audit(publication_id,approval_ref,actor_ref,row_counts)
    values(pub,p_approval,p_actor,counts);
  return counts;
end $$;
revoke all on function public.lean_scoped_release(text,text,text[],jsonb,text,text,text),
  public.lean_scoped_export(text,text,text[],text,text) from public,anon,authenticated,service_role,lean_posthog_reader;
commit;
